proxy:
  secretToken: "3f96a16ffe3909b7c91692686ac5f2e4a89ab57037d94e36b02bbc7a7a59edf2"

singleuser:
  defaultUrl: "/lab"
  serviceAccountName: dask-user
  image:
    name: ogrisel/dask-notebook-extended
    tag: latest

hub:
  extraEnv:
    JUPYTER_ENABLE_LAB: 1
  extraConfig: |
    c.KubeSpawner.cmd = ['jupyter-labhub']

auth:
  admin:
    users:
      - ogrisel
